version: "3.3"

services:
  pets-api:
    image: openjdk:17
    container_name: "pets-api"
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - "./target/apteka-1.0.jar:/app.jar"
    entrypoint: [ "sh", "-c", "java  -jar /app.jar" ]